activation: gelu
alpha:
- 1.0
- 1.0
- 1.0
- 1.0
- 1.0
ambient:
- 4
batch_sizes:
- 64
- 50000
coefficients:
- 1.0
- 1.0
- 1.0
- 1.0
- 1.0
kmoduli:
- 1.0
monomials:
- - 5
  - 0
  - 0
  - 0
  - 0
- - 0
  - 5
  - 0
  - 0
  - 0
- - 0
  - 0
  - 5
  - 0
  - 0
- - 0
  - 0
  - 0
  - 5
  - 0
- - 0
  - 0
  - 0
  - 0
  - 5
n_epochs: 300
n_fold: 3
n_hidden: 64
n_in: 10
n_layers: 3
n_out: 9
